apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  namespace: "namespace3"
  labels:
    name: deployment-consumer
spec:
  selector:
    matchLabels:
      app: deployment-consumer
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-consumer
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          {{- if .command }}
          command: 
            {{- toYaml .command | nindent 12 }}
          {{- end }}
          {{- if .env}}
          env:
            {{- range .env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | default "" }}
              {{- if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
                {{- toYaml .readinessProbe.exec.command | nindent 14 }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            successThreshold: {{ .readinessProbe.successThreshold }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              port: {{ .livenessProbe.httpGet.port }}
              path: {{ .livenessProbe.httpGet.path }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            successThreshold: {{ .livenessProbe.successThreshold }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
        {{- end }}
