apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deployment-consumer
  namespace: "namespace3"
  labels:
    name: deployment-consumer
spec: 
  selector:
    matchLabels:
      app: deployment-consumer
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: deployment-consumer
    spec:
      containers: 
        - name:  deployment-container
          image: bala699/cve-consumer:latest
          env:
            - name: DB_USER
              value: cve_user
            - name: DB_PASSWORD
              value: cve123
            - name: DB_PORT 
              value: "5432"
            - name: DB_HOST
              value: "cve-webapp-processor-pgpool.namespace3.svc.cluster.local"
            - name: DB_NAME
              value: "cve"
            - name: KAFKA_HOST
              value: "kafka.namespace2.svc.cluster.local:9092"
            - name: KAFKA_PASSWORD
              value: "rlKn8lPKKX"
            - name: KAFKA_USER
              value: "user1"
            - name: TOPIC_NAME
              value: "cve"
            
          readinessProbe:
            exec:
              command: 
                - /usr/local/bin/db_check.sh
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 80
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3



            
